apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-cluster-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: aks-cluster-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
